### ISSUE TITLE
Sponge Server crash

### ISSUE THREAD

**Issue by LXGaming** [Bastian/bStats-Metrics#24] opened 2017-09-01 08:25 UTC
When adding a plugin which uses bStats to a server that already has a different plugin using bStats the server crashes.

I believe this is due to the newly added plugin getting loaded first which is causing an error when loading the second plugin.

This can be replicated by setting the class in temp.txt to that of the plugin which gets loaded second.

Crash Log: https://pastebin.com/CxxTj5hQ
Crash Log (This paste won't expire): https://pastebin.com/HbzqsKq7

**Comment by DoNotSpamPls** [comment] 2018-03-24 10:36
`Caused by: java.lang.ClassNotFoundException: net.mohron.skyclaims.metrics.Metrics`

That message is usually shown when the bStats Metrics class is shaded improperly. Can it be reproduced with all plugins, or just this one? I'm sure there are a lot of servers using more than 1 bStats plugin

**Comment by DoNotSpamPls** [comment] 2018-10-07 12:42
#38 should have fixed this issue.

**Comment by Bastian** [comment] 2018-10-28 16:45
Yes. 
Should be fixed in version 1.3

**Closed by Bastian** 2018-10-28 16:45 UTC
Labels: bug
